### PR TITLE
uint256: optimize ExtendSign

### LINKED ISSUE #102: Optimize ExtendSign()
The current implementation is done by bits manipulation on whole 256-bit values (as you would do it for architecture native integers). There exists more efficient implementation which handles each of 4 64-bit words separately. This has been implemented in evmone in https://github.com/ethereum/evmone/pull/390.

### PR DESCRIPTION
**Pull request by AaronChen0**
close #102

## Test
```
go test ./...
```
returns
```
ok  	github.com/holiman/uint256	0.976s
```
## Benchmark
code:
```
func BenchmarkExtendSign(bench *testing.B) {
	a := new(Int).SetBytes(hex2Bytes("f123456789abcdeffedcba9876543210f2f3f4f5f6f7f8f9fff3f4f5f6f7f8f9"))

	result := new(Int)
	n := NewInt(0)
	bench.ResetTimer()
	for i := 0; i < bench.N; i++ {
		result.ExtendSign(a, n)
	}
}
```
```
goos: linux
goarch: amd64
pkg: github.com/holiman/uint256
cpu: AMD Ryzen 7 7735H with Radeon Graphics         
              │     old     │                 new                 │
              │   sec/op    │   sec/op     vs base                │
ExtendSign-16   7.875n ± 1%   2.859n ± 1%  -63.70% (p=0.000 n=10)

              │    old     │              new               │
              │    B/op    │    B/op     vs base            │
ExtendSign-16   0.000 ± 0%   0.000 ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal

              │    old     │              new               │
              │ allocs/op  │ allocs/op   vs base            │
ExtendSign-16   0.000 ± 0%   0.000 ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal
```

### CODE REVIEW

**Comment by holiman** [comment]
I added a benchmark:
```
[user@work uint256]$ benchstat bench.extend.1 bench.extend.2
name          old time/op  new time/op  delta
ExtendSign-8  13.0ns ±22%  12.0ns ± 6%  -7.35%  (p=0.030 n=8+10)
```

I didn't use the same one you did: yours was skewed to only ever bench with `n=0`. So my speedup is a bit less, I'd be curious to see if you get roughly the same improvements as me with this benchmark, or if you still get something much larger?

**Comment by AaronChen0** [comment]
Using your benchmark, I still get much better performance.
```
goos: linux
goarch: amd64
pkg: github.com/holiman/uint256
cpu: AMD Ryzen 7 7735H with Radeon Graphics         
              │     old     │                 new                 │
              │   sec/op    │   sec/op     vs base                │
ExtendSign-16   8.175n ± 2%   3.557n ± 1%  -56.49% (p=0.000 n=10)

              │    old     │              new               │
              │    B/op    │    B/op     vs base            │
ExtendSign-16   0.000 ± 0%   0.000 ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal

              │    old     │              new               │
              │ allocs/op  │ allocs/op   vs base            │
ExtendSign-16   0.000 ± 0%   0.000 ± 0%  ~ (p=1.000 n=10) ¹
¹ all samples are equal
```

**Comment by holiman** [comment]
> What system are you testing on?

It's a lenovo x1 carbon gen 10, `12th Gen Intel(R) Core(TM) i7-1270P1`, but it's a bit special because I'm running on qubes os, so it's on a virtual machine.

**Review by holiman — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
